language: python
python:
  - "2.7"

sudo: required

services:
  - docker

before_script:
  - docker-compose build
  - pip install flake8
  - pip install pylint

script:
 - docker run techmiyacommercials_app python manage.py test
 - python -m flake8
 - find . -iname "*.py" | xargs pylint --rcfile tests/.pylintrc

after_script:
  - docker-compose kill
